name: release

on:
  release:
    types: [created]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and release
      uses: wangyoucao577/go-release-action@v1.30
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://go.dev/dl/go1.19.linux-amd64.tar.gz"
        ldflags: -X "main.version=${{ github.ref }}"
        project_path: "./client"
        binary_name: "trav"
        asset_name: trav-${{ matrix.goos }}-${{ matrix.goarch }}
